### ISSUE TITLE
init script prevents docker to stop container

### ISSUE THREAD

**Issue by crblanaru** [odarriba/docker-timemachine#1]
Dear Dev,

I have noticed that the init script will not allow the container to be stopped any more. It might be worth while to put the action in rc.local so that docker stop/kill command work.

Regards,
Cristian

**Comment by odarriba** [comment]
Hi Cristian!

Thanks for taking a while to report this :)

I'll take a look into it, because I think I have used the `docker stop`command before and it worked!
I'll try it later and told you if I can replay the problem.

Thanks!

**Comment by crblanaru** [comment]
Just realised that I was to thorough in describing how I tested:

Linux homeserver 3.19.0-28-generic #30~14.04.1-Ubuntu SMP Tue Sep 1 09:32:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Installed containers as per your instructions and ran them. 
Copied the script to the init folder and restarted the machine -> After reboot when I issue docker stop/kill I find that the containers are still running using docker ps

I remove the init script and reboot the machine -> When I issue the command the container stops

To fix:
I moved the action to rc.local. This means that the container is started but I do not lose any functionality.

Either way, it is not a major problem. 

Thank you for all the work you have put into this container. It's been working great.

Cristian

**Comment by odarriba** [comment]
Hello Cristian,

Sorry for the delay, I have been very busy these days.

Would you like to contribute making a pull-request of the improvement you mentioned?
If there is any problem or you just don't want, dont worry, I can find time to make the change.

Thank you for your support and bug-hunting :D

Óscar

**Comment by odarriba** [comment]
Hello!

First of all, sorry for the delay.

I've changed part of the functionality to make use of the existing `netatalk` service management script, so the container can stop and start without problems.

In my server it runs ok now, can you check if it works?

**Comment by odarriba** [comment]
@crblanaru : I mark this issue as closed, if it the latest image doesn't solve the problem, please, let us know to re-open :)
