### ISSUE TITLE
Multi-user support?

### ISSUE THREAD

**Issue by ajarara** [odarriba/docker-timemachine#11]
As it stands now, the instance only has the capability to interact with one client. Are users supposed to run multiple instances of this for each client who needs this?

It looks like afp.conf has the capability to handle multiple clients.

Implementing this would require a rather significant change to the UI, and might be best addressed in a fork. What do you think?

**Comment by odarriba** [comment]
As you said, afp allows for multi-user configuration. This container is single-user just because it uses configuration variables to create that `afp.conf` file.

In order to do this, I think the best option is to allow user to "mount" a custom `afp.conf` file. What do you think? 

If you want to create a fork and develop this feature, please be welcome.

Thanks!

**Comment by ajarara** [comment]
I was hoping you'd say that. I agree that mounting an afp.conf file (either within the same directory as the Dockerfile, named afp.conf, as a default, or overridden by some -e flag pointing to the file) is the best solution.

Would you like the single user config to stay untouched?

**Comment by odarriba** [comment]
I think that we can modify the startup script: if there is a previous afp.conf, don't generate a new one. 

With this change and a mountpoint, we can conserve both functionalities. What do you think?

If you finally do the PR, please update the README with these instructions and feel free to add yourself to contributors list. It's a great feature.

**Comment by ajarara** [comment]
Sorry for the lack of response, midterms rolled around last week.

Unfortunately, it looks like I won't have access to a machine running OS X until Thanksgiving. I have a couple of branches that I'd like to run tests on, but can't really provide a polished, tested PR, I can't tell if they work or not. If you're willing to wait that long, I'd be happy to hack on this over the coming break, but if anyone else in the meantime wants to do this, more power to them.

**Comment by odarriba** [comment]
Don't worry @alphor, I'm pretty sure that this can wait a bit longer.
But, if any other is interested in this functionality, fell free to contribute as @alphor said.

Thank you for your update and your work! It will be awesome!

**Comment by odarriba** [comment]
Hello!

I have updated the image, so now users can be added executing a simple command (and the README file is updated too).

So now the container start with no user on it, and the users can be added as you wish.

I think this solves the issue, so I close it.

Thanks!

**Comment by ajarara** [comment]
This looks great! Well done.

**Comment by Dids** [comment]
@odarriba Users aren't persisted though, right?

**Comment by odarriba** [comment]
@Dids Users are persisted while the container isn't deleted and created again. They are persisted **inside** the cointainer, but not in the external volume, so they should persist while the container isn't deleted.

**Comment by Dids** [comment]
@odarriba I know, I just wouldn't call that persisting. ;)
In my case I have a systemd service that's recreating the container on boot/shutdown, but I went with an insecure hack for now, and simply added an extra "post startup" step for the service, which adds the users.

**Comment by odarriba** [comment]
@Dids As the configuration depends on having a user created inside the container, the configuration is really hard and insecure to store, as it would require storing the passwd file or the user's password directly.

I can recommend you two viable configurations:

1. Create the container storing the sfpd configuration file and the container's passwd file in a volume mapped to your machine
2. Start the container with the setting of autostart with the local machine, so you wouldn't need a systemd service, and you will ever have the same container running (which you only need to configure once).

**Comment by Dids** [comment]
@odarriba Thank you, the first one sounds like it'd work better for my environment. :)

**Comment by odarriba** [comment]
Glad that helps! Only one thing: remember you should set the right permissions, as the passwd file is very sensitive :)
