### ISSUE TITLE
Latest changes broke docker-compose compatibility

### ISSUE THREAD

**Issue by RobTS** [odarriba/docker-timemachine#12]
Just rebuilt my containers and realized I can't log into the time machine any more. Seemingly, the latest change to add users removed the AFP_LOGIN, AFP_PASSWORD and AFP_NAME attributes. Still investigating, will update this issue once I know for sure. Going back to old version in the meantime.

**Comment by odarriba** [comment]
That's right!

**Comment by odarriba** [comment]
That's right!

https://github.com/odarriba/docker-timemachine/blob/dc9cd2add4186b5bf799b50bab62761b80b8243f/entrypoint.sh

I haven't thought about that possible use-case.
I will restore the functionality in the next days.

Thanks!!

**Comment by odarriba** [comment]
Hello @RobTS !

I have just added that forgotten functionality, and it should be building in docker hub right now.

Can yo try again when compiled?

Thanks!

**Comment by RobTS** [comment]
Hey, thanks for the help. Just got around to trying it, unfortunately, it's still failing. This time not with an auth, but a connection problem. Docker logs state the following: 
![screen shot 2017-01-11 at 11 28 54](https://cloud.githubusercontent.com/assets/1608080/21845050/4c5eb0ca-d7f1-11e6-90fd-2788bb8c9b91.png)

As a workaround suggestion, a tag on build bt3piatgu8decpaxm9qj7h6 would already help me a great deal.

Config matches the one of my public homeserver repo, it may help you find the issue: https://github.com/RobTS/homeserver_template

**Comment by odarriba** [comment]
Hi again!

Sorry for the delay. I have test it right now and changed the service launching structure to avoid these errors.

According to my tests, it should work right now. Can you confirm it?

Regards!

**Comment by odarriba** [comment]
I suppose this is working right now, So I'm closing the issue. Please, If it doesn't, just comment here and reopen the issue.

Regards!
