### ISSUE TITLE
Does not seem to work. Needs troubleshooting guide.

### ISSUE THREAD

**Issue by ralfbiedert** [odarriba/docker-timemachine#15]
Server: 
- Ubuntu 16.4.2 LTS
- Latest **docker-timemachine**, followed instructions
- `avahi-daemon` up and running (according to instructions)
- Firewall (`ufw`) disabled 

MBP:
- Running 10.12.3
- All firewalls disabled (system + Little Snitch) 
- Running on same network 

Result:
- MBP (Settings -> Time Machine) does not detect any Time Machine drives

**Update**
- Alrighty, if I manually mount the volume first (`afp://myhost`) I can connect to it.
- Makes me wonder, is this supposed to create a Time Machine disk, or just an AFP volume? In that case the instructions should be clearer how to connect to it!

**Comment by stephen-mw** [comment]
@ralfbiedert the reason is because your time machine server is not on the same network as your laptop, so it can't see afp broadcasts. I don't know for sure, but you can get around this by running in ```--net=host``` mode.

**Comment by odarriba** [comment]
Hi!

Some tips:

* If you have avahi-daemon configured, you should be able to activate `ufw` enabling `avahi-daemon` and `netatalk` ports. It should work fine.

* The idea of using avahi-daemon installed in the bare metal server is to avoid having to execute the container with `--net=host`, which a potentially insecure flag (/cc @stephen-mw). But, as the last option to check things out, it should be fine. You just should know what you are enabling.

* A Time Machine network disk is *just* a disk image in an AFP volume that supports the correct level of encryption. So to be recognised by the TimeMachine daemon, you *should* mount the unit manually for the first time, configure TimeMachine on your computer, and then the OS will do that for you automatically.

Hope this helps and sorry for the lack of instructions (if you feel good updating the README, please feel free to do a PR!).

And thank you for your feedback! You rock!

**Comment by ralfbiedert** [comment]
Added a pull request (#16) for an updated README.

**Comment by odarriba** [comment]
Merged, thanks a lot! Closing this issue...
