### ISSUE TITLE
Backup failed due to space restriction

### ISSUE THREAD

**Issue by AGresvig** [odarriba/docker-timemachine#17]
I got this up and running, thanks for a great image!

But after TM backup has initialized, I get an error:

> The backup disk needs 152,06 GB for the backup but only 87,19 GB are available. Select a larger backup disk or make the backup smaller by excluding files

I specified a mountpoint of 300000 (300GB) when creating my user. The mount point is on a mdadm array with 2.5TB free so there must be some restriction in the image.

Any ideas?

**Comment by stephen-mw** [comment]
Hi @AGresvig. Please paste the output of the following command so we can examine your afp settings. (Change any information you don't want public):

```
docker exec <running container id> cat /etc/afp.conf
```

**Comment by AGresvig** [comment]
Thanks for replying. Here you go:

```
[Global]
    mimic model = Xserve
    log file = /var/log/afpd.log
    log level = default:warn
    zeroconf = no

[aksel]
    path = /path/to/MyTimeMachineBackup
    time machine = yes
    valid users = myUser

    vol size limit = 300000
```

**Comment by stephen-mw** [comment]
That looks fine to me. When you connect directly to your backup via afp://, what metadata does it say about your volume? Does it correctly identify it as the size you've configured?

**Comment by odarriba** [comment]
That should, teorically, works fine. Is there any space restriction in the volume? Take care about per-user restrictions: Docker files aren't stored as your current user (even if the TimeMachine user is called the same as your local user).

**Comment by AGresvig** [comment]
> what metadata does it say about your volume

not quite sure how to see that? Finder tells me nothing of interest..

>  Is there any space restriction in the volume? Take care about per-user restrictions

I havent set up any space restrictions, and I checked using `quota`. 

When creating the container I specified `PGID` and `PGID` env vars, setting group and user to my current user. The TimeMachine backup directory is writeable only by my user and corresponding group

**Comment by krishofmans** [comment]
Were you able to resolve this issue? I'm experiencing a similar issue: 
![image](https://cloud.githubusercontent.com/assets/999774/24841145/0710aeb6-1d7d-11e7-938c-a1ec3e59baef.png)

While I've set no restriction on size, and there is a couple of TB free on the server.

Thanks.

**Comment by AGresvig** [comment]
Nope, I gave up

**Comment by odarriba** [comment]
Hey there @AGresvig and @krishofmans !

There were an issue with regards of the meaning of AFP_NAME environment variable when using the image without manually creating the accounts.

If you were using the image with the ENV variable, the patch may possibly solve your issue.

Hope it helps,
Oscar

**Comment by odarriba** [comment]
Closing the issue. Please ping me if it's not solved.
