### ISSUE TITLE
AFP_NAME doesn't seem to work anymore

### ISSUE THREAD

**Issue by jayjanssen** [odarriba/docker-timemachine#20]
I upgraded to your latest recently (from last July) and my TM share name changed to simply 'tm'. I am setting AFP_NAME to 'TimeMachine'.

**Comment by odarriba** [comment]
Here there is an error in fact. As I can see [here](https://github.com/odarriba/docker-timemachine/blob/master/entrypoint.sh#L20) and [here](https://github.com/odarriba/docker-timemachine/blob/master/bin/add-account), we are using AFP_NAME as the mountpoint, which should be an absolute path.

I'll fix this this week (it's a bit busy one). If you just avoid using env variables and just use the command line option, it should be fine, but the server name will appear as your user 🤔

**Comment by jayjanssen** [comment]
Ok, thanks.  I'm using docker-compose, hence the need for ENVs.  Happy to test when you have a fix, and I appreciate the image.

**Comment by odarriba** [comment]
Hey @jayjanssen !

Sorry for the delay. It has been a tough June.

The image has been updated so when using environment variables the mountpoint selected is always the root of the external volume. And now the AFP_NAME attribute do it's work as expected :)

Does it solve your issue?

**Comment by odarriba** [comment]
Closing the issue. Please ping me if it's not solved.

**Comment by jayjanssen** [comment]
Hi -- yes, the latest image seems to have fixed this.  I am able to backup to it just fine, thank you.
