### ISSUE TITLE
Unable to support encrypted TM Backups

### ISSUE THREAD

**Issue by jayjanssen** [odarriba/docker-timemachine#21]
On a previous version, I was able to enable encrypted backups from my Mac just fine.  With the new version I am unable to select this.

**Comment by jhaals** [comment]
I started using the latest docker container today, encrypted backups works fine for me

**Comment by odarriba** [comment]
They should not be any issue, because that depends only in your Mac, not in the server side. Any updates on this?

**Comment by jayjanssen** [comment]
Hi -- could have been user error, I'm not sure.  I also had issue #20 at the same time, though when I reviewed your code updates it seemed as if that should have worked just fine.  Let me revisit the update and get back to you.

**Comment by odarriba** [comment]
As commented on #20, there is an error on the usage of `AFP_NAME`, that could lead to an invalid mount path, and that can lead in impossibility to write anything, including encrypted disks.

**Comment by odarriba** [comment]
As commented on #20, the issue with the ENV variable should be fixed within the latest image.
Can you confirm too @jayjanssen ?

**Comment by odarriba** [comment]
Closing the issue. Please ping me if it's not solved.
