### ISSUE TITLE
Updating the Raspberry Pi version

### ISSUE THREAD

**Issue by hmbrg** [odarriba/docker-timemachine#25]
The Raspberry Pi ARM version hasn't been merged with the master for a while now. 
Is there a specific reason for that, or was something changed that is not supported by the ARM architecture?

**Comment by odarriba** [comment]
It become different some time ago, and now it's a bit hard to maintain both on sync.

I have in mind to move both versions to master in a near future and use same codebase in both images. As the base image don't change frequently (the main changes are on additional scripts) it should be good.

**Comment by odarriba** [comment]
@brighthero It has been updated today.

Now there are two different Dockerfiles on the master branch, and both images are synced.

Also, an updated image has been pushed to the registry: https://hub.docker.com/r/odarriba/timemachine-rpi/
