### ISSUE TITLE
How to delete user account?

### ISSUE THREAD

**Issue by metalcamp** [odarriba/docker-timemachine#27]
Is there an option to delete user account and/or change credentials (password)? 
Edit: nevermind, I looked at Dockerfile and will code a solution similar to add-account. Is there anything I should be aware of before coding?

**Comment by odarriba** [comment]
Thanks for opening the issue!

Just deleting the user from the system should be enough (i think, needs testing). And also would be good to remove it from the afp config file, but that's much more difficult :/
