### ISSUE TITLE
Use Disk -- Connect stuck in loop

### ISSUE THREAD

**Issue by ghost** [odarriba/docker-timemachine#32]
This is my first time using docker-timemachine and I haven't been able to get things working.  On the client machine, I connect to the server using cmd+k and "afp://192.168.1.x". Then in the Time Machine window, I click "Select Backup Disk".  I see my disk here, "/path/to/my/shared_disk".  I select the disk and click "Use Disk". I am now asked for a username and password.  I enter the username and password and click "connect" which takes be to the previous screen where I select my disk again.  This repeats. 

I'm not well versed in Mac.  running the following command `log show --predicate 'subsysten == com.apple.TimeMachine"'` --debug` on the client system shows the follow log which is the only thing in the correct time window.

`2017-11-03 19:10:55.303516-0200 0x13be    Error    0x0    340    UserEventAgent: (TimeMachine) [com.apple.TimeMachine.TMLogError] com.apple.TMHelperAgent.SetupOffer enabled`

**Comment by odarriba** [comment]
Closing as no body have this issue and we cannot replicate it.
