### ISSUE TITLE
Avahi on Windows?

### ISSUE THREAD

**Issue by ScottPierce** [odarriba/docker-timemachine#34]
If I don't use Avahi, am I going to have to manually connect to the server every time I want to backup, or will mac do that for me? I assume not.

I'm trying to host this on a Windows server. Would I be able to get auto-connection / discovery working on Windows? I'm assuming it'd have to be through something besides avahi?

**Comment by odarriba** [comment]
avahi enables autodiscovery in the local network (aka, appearing in Finder automatically). besides that, you can autoconnect using the IP address of your server (must be static) and the backups should work fine.

Hope that helps :)

**Comment by ScottPierce** [comment]
Avahi doesn't seem to be available for a windows host. Is there anything I could use as an alternative to avahi?

**Comment by odarriba** [comment]
It doesn't look like there is any native option: https://learn.adafruit.com/bonjour-zeroconf-networking-for-windows-and-linux/overview#microsoft-windows

But, if Docker on windows enables that (I don't really know, haven't tried) you can spawn a container con privilege access to the network, and install avahi there. That would enable avahi to send its service announcements through the network.

Example: https://hub.docker.com/r/danisla/avahi/ (look at the `--net host` in the docker run command)
