### ISSUE TITLE
Add host allow/deny config?

### ISSUE THREAD

**Issue by trifle** [odarriba/docker-timemachine#35]
Hi, thanks for the very useful image!

Netatalk offers config options for allowing/denying specific hosts or whole subnets, which sometimes is very handy:

http://netatalk.sourceforge.net/3.0/htmldocs/afp.conf.5.html

```
hosts allow = IP host address/IP netmask bits [ ... ] (V)
Only listed hosts and networks are allowed, all others are rejected. The network address may be specified either in dotted-decimal format for IPv4 or in hexadecimal format for IPv6.

Example: hosts allow = 10.1.0.0/16 10.2.1.100 2001:0db8:1234::/48

hosts deny = IP host address/IP netmask bits [ ... ] (V)
Listed hosts and nets are rejected, all others are allowed.

Example: hosts deny = 192.168.100/24 10.1.1.1 2001:db8::1428:57ab
```

It would be nice to expose this via a parameter as well!

PS: This is a volume-level parameter, so it would need to be injected into the `[<<volume-name>>]` section in `add-account`.

**Comment by odarriba** [comment]
I think at this point of granularity in config, the easiest way is just copy `afp.conf` from the container to your computer, set the config as you need it and then mount it in your continer.

Thanks!
