### ISSUE TITLE
user accounts don't survive container re-creations 

### ISSUE THREAD

**Issue by captn3m0** [odarriba/docker-timemachine#36]
After a docker system prune, timemachine does not seem to be able to get back to normal since the user accounts are lost.

I was considering making `/etc/afp.conf` a volume mount, but that won't suffice since the user accounts will also need to be re-created.

I'm using multiple user accounts otherwise the startup environment variables would have worked.

**Comment by odarriba** [comment]
Hey there!

As you pointed, the only quick solution you can find at the moment is to use a single user with the ENV vars or creating the accounts manually.

The only way I can found around this at the moment is to create some kind of script that reads a config file and spawns everything needed. It could work by putting that file in an external volume.

However, I don't have time at this moment to do it, so your best chance is probably scripting the spawning of the container, running also the commands required to create the users.

Hope it helps,
Oscar

**Comment by captn3m0** [comment]
Thanks. I'm [looking at the entrypoint](https://github.com/odarriba/docker-timemachine/blob/master/entrypoint.sh) and considering replacing it entirely with a script that creates the correct users.

I'm also considering moving the afp config to a simple file mount. Any reason why [it is in the entrypoint and not on the Dockerfile](https://github.com/odarriba/docker-timemachine/blob/89b3f34e968920cf3aaa066468385b49d0cdc2af/entrypoint.sh#L5-L17)? Looks fairly static, so it will remove the afp mount as a plus for me. I'll file a PR with just this one change if you agree.

**Comment by odarriba** [comment]
Not really, it's just a way to clean the afp config file each time the container is restarted. I think it could be removed and added on the Dockerfile itself safely.

And of course PRs are welcome! Thanks!

**Comment by captn3m0** [comment]
Closing this issue as I have a solution in progress. I'll add it to the wiki and file a PR on README documenting it once I'm done.
