### ISSUE TITLE
Multiple user problems

### ISSUE THREAD

**Issue by schander** [odarriba/docker-timemachine#39]
I have used the add-account script to setup 2 user accounts.
These are present in the afp.conf file.
The problem that I'm facing is that I can only login to the user account create last, e.g.
add-account user1
login available from mbp
add-account user2
login available from mbp
if i now try to connect from mbp with user1, I get the following error:
There was a problem connecting to the server <server>
In the afp log I see 
Apr 23 06:28:56.276443 afpd[70] {dsi_stream.c:504} (error:DSI): dsi_stream_read: len:0, unexpected EOF

Any thoughts?

**Comment by schander** [comment]
I think the solution is that the **VOL_NAME** in _bin/add-account_ cannot be the same for any two users, otherwise netatalk picks up the last one with that **VOL_NAME**
I realised this when reading:
[Netatalk sourceforge page](http://netatalk.sourceforge.net/3.0/htmldocs/afp.conf.5.html)
In the parameters section it says:

> "No two volumes may have the same name."

As soon as I renamed one of the sections I was able to login as the particular user, without a problem.

**Comment by odarriba** [comment]
Looks like you already fixed it. Thanks for commenting the solution here!
