### ISSUE TITLE
GID & UID Variables in docker-compose

### ISSUE THREAD

**Issue by hongkongkiwi** [odarriba/docker-timemachine#40]
Hi there,

Can you add the ability to set a specific UID & GID when creating the docker via environment variables? Right now this can only be done if we manually create the user using the script.

The usecase is inside the docker-compose.yml file

**Comment by odarriba** [comment]
That is not supported at the moment, but can be easily added by modifying the start script, but that requires testing it, updating the README and doing a PR.

I'm setting this as help wanted in case anyone wants to do it.

Thanks!
