### ISSUE TITLE
Share doesn't exist

### ISSUE THREAD

**Issue by jknsware** [odarriba/docker-timemachine#43]
Here are the steps I followed:

Run the container.
`$ docker run -h timemachine --name timemachine --restart=unless-stopped -d -v /mnt/user/timemachine:/timemachine -p 548:548 -p 636:636 odarriba/timemachine`

Confirm it's working.

Add the user.
`$ docker exec timemachine add-account backup password tm /timemachine/backup`

And this is what I get when I try to login...

![image](https://user-images.githubusercontent.com/13934735/42922449-2d229a88-8ae6-11e8-8ddf-01aaeef94962.png)

Any clues as to what might be going on here?

**Comment by jknsware** [comment]
Must have been the server I was using as my Docker host. Switched to another one and it's working perfectly.

**Comment by jordanpotter** [comment]
I came across this same issue and found that the `/timemachine` volume I was mounting only allowed for root access. Modifying the permissions via `chmod` corrected the issue for me.
