### ISSUE TITLE
Services do not start after a reboot of the container

### ISSUE THREAD

**Issue by crblanaru** [odarriba/docker-timemachine#5]
I was puzzled why when my container rebooted (either because I was shutting down the container or because of machine reboot) the netatalk service inside the container would not start. 
I believe that this is caused by a stale lock file in /var/lock/netatalk

I have altered the start_services.sh to remove that file before starting the service and it seems that the issue is fixed for me.

What are your thoughts on this?

**Comment by gregturn** [comment]
I saw mine seize up as well. I didn't have time to investigate. But if this fixes it, that would be awesome. PR?

**Comment by odarriba** [comment]
Please, submit a PR so we can check it and improve the container.

And thanks for your research work :)

**Comment by odarriba** [comment]
Solved at PR https://github.com/odarriba/docker-timemachine/pull/6 :)
