### ISSUE TITLE
Time machine incorrectly reports disk size when using an external volume.

### ISSUE THREAD

**Issue by scottyphillips** [odarriba/docker-timemachine#50]
Hi, thanks for the container, seems to work well, except there is a slight flaw - the network volume is incorrectly reporting free space when I try to use a much larger external USB drive. I am running a high capacity 6TB USB drive but the mounted volume on my mac is only reporting the total capacity of the built in hard drive on my server which is much lower..

**Comment by scottyphillips** [comment]
I closed the issue because I have worked around the problem using a privileged docker container which exposes all the hosts devices

**Comment by jpheuz** [comment]
I am having the same issue. I also added the `--privileged` flag but it does not change. I have only 34GB available, though there are more than 500GB free.
What steps did you exactly do?

**Comment by ybaidiuk** [comment]
I have same problem. --privileged not work

**Comment by ybaidiuk** [comment]
I found solution:
add user command was wrong 
**Last argument need be under /timemachine folder**
Wrong:  docker exec timemachine add-account pi passBLAbla123  tm /home/pi/tm

**Correct: docker exec timemachine add-account pi passBLAbla123  tm /timemachine**

But now i have another issue: a lot of erros by adding user
chown: /timemachine: Operation not permitted
I tried 4 days get SMB server working correctly with exFat, (hate Microsoft!!!)
So i slow "operation not permitted with ext4 format. "
But now if Raspberry Pi go down I would not be able to restore my Mac with direct connection.
...
