### ISSUE TITLE
Can't get docker container to use external drive

### ISSUE THREAD

**Issue by kippjohnson** [odarriba/docker-timemachine#53]
I have a 3.6 tb drive mounted on `/mnt/sdb/`
The server root is /, a 50% filled 502gb SSD

Following command to start the docker:
`docker run -h timemachine --name timemachine --restart=unless-stopped -d -v /mnt/sdb/timemachine/ -it -p 548:548 -p 636:636 --ulimit nofile=65536:65536 odarriba/timemachine`

Following command to add the user:
`docker exec timemachine add-account kwj <PASSWORD> rcvol /mnt/sdb/timemachine/backup`

The root disk keeps showing up in time machine instead of the external volume, see picture.
Any ideas what I am doing wrong?

<img width="359" alt="image" src="https://user-images.githubusercontent.com/6765617/54768493-a3d0d400-4bd5-11e9-97c4-05a57808b09e.png">

**Comment by ferdinand** [comment]
Your -v flag is missing the mount path in the container. This should work:

```
docker run -h timemachine --name timemachine --restart=unless-stopped -d -v /mnt/sdb/timemachine/:/tm -it -p 548:548 -p 636:636 --ulimit nofile=65536:65536 odarriba/timemachine
docker exec timemachine add-account kwj <PASSWORD> rcvol /tm/backup
```

**Comment by JonathanPaulick** [comment]
> Your -v flag is missing the mount path in the container. This should work:
> 
> ```
> docker run -h timemachine --name timemachine --restart=unless-stopped -d -v /mnt/sdb/timemachine/:/tm -it -p 548:548 -p 636:636 --ulimit nofile=65536:65536 odarriba/timemachine
> docker exec timemachine add-account kwj <PASSWORD> rcvol /tm/backup
> ```

Also make sure you have proper permission for the external drive. I was running into this problem with Ubuntu.

**Comment by odarriba** [comment]
Any updates on this? Did @ferdinand or @JonathanPaulick comments help?

**Comment by kippjohnson** [comment]
Yes, it does appear to be working now. I think I followed @ferdinand's advice. Thanks to everyone.
