### ISSUE TITLE
how to mount disk correctly?

### ISSUE THREAD

**Issue by a-x-** [odarriba/docker-timemachine#57]
I have hdd that I use with timemaschine via usb connection
Can I use it w/o re-formatting?

Something like this?: https://askubuntu.com/questions/332315/how-to-read-and-write-hfs-journaled-external-hdd-in-ubuntu-without-access-to-os

**Comment by odarriba** [comment]
You should be able to use it as long as Docker daemon (aka the host) can access to it.
