### ISSUE TITLE
multiple disks

### ISSUE THREAD

**Issue by hryamzik** [odarriba/docker-timemachine#62]
Can I use this image to serve multiple disks? If so, how to configure this with ENV vars?

**Comment by odarriba** [comment]
Depending on what you want to do, maybe you can configure this through ENV vars.

You can do multiple things:
 - Mount all disks in different paths inside a folder, and use that folder to be shared using one user (created using ENV vars or the add user script).
 - Mount all disks in different paths of the Docker container and use different users to share them (one user per disk), all of them created using the add user script.
 - You can even try to have different shares on the same user, adding the same user multiple times with different share volumes (using the add user script) - but i´m not completely sure about if this would work.

Hope it helps!
